server {
    listen 80;
    server_name localhost;

    # Блок для обработки запросов к бэкенду

    location ~* "/api/" {
        proxy_pass http://monolith-backend:9009;
        include /etc/nginx/snippets/proxy-headers.conf;
    }

    # location ~* "/api/search/incidents/" {
    #     proxy_pass http://monolith-backend:9009;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }

    # location ~* "/api/|/admin/|/ckeditor/|/metrics/" {
    #     proxy_pass https://im-dev.mlg.ru;
    #     include /etc/nginx/snippets/proxy-headers.conf;
    # }

    # Блок для обработки запросов к фронту
    # location / {
    #     proxy_pass https://im-dev.mlg.ru;
    #     include /etc/nginx/snippets/proxy-headers.conf;
    # }
    location / {
        proxy_pass http://monolith-frontend:80;
        include /etc/nginx/snippets/proxy-headers.conf;
    }
}
