server {
    listen 80;
    listen [::]:80;
    server_name presentation.paralipupa.ru;

    access_log /var/log/nginx/presentation.access.log;
    error_log  /var/log/nginx/presentation.error.log warn;

    root /usr/share/nginx/html/presentation;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
