server {
    listen 8080;
    listen [::]:8080;
    server_name _;

    access_log /var/log/nginx/prez.access.log;
    error_log  /var/log/nginx/prez.error.log warn;

    root /usr/share/nginx/html/prez;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
